### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by tqphan** [kmcnaught/SmoothMousePlugin#1]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0012	The type 'Timestamped<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reactive.Linq, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.	SmoothMouse	C:\Users\q\Downloads\SmoothMousePlugin\MouseInput.cs	12	

```

I think I might installed wrong version of System.Reactive.Linq? I tried System.Reactive.Linq 4.41 and 4.0.0

Which version is required?

**Comment by tqphan** [comment]
NuGet\Install-Package Rx-Linq -Version 2.2.5

**Comment by kmcnaught** [comment]
glad to see someone playing with the plugin system :-)

**Comment by tqphan** [comment]
Thanks for creating this plugin system. I can now use the unsupported trackers with 4.1
